### ISSUE TITLE
API 2.5 vs 3.0

### ISSUE THREAD

**Issue by Brown-onion** [AlexeyMal/esp8266-weather-station#1]
The API request for 2.5 seems to not be supported anymore.
I believe API 3.0 is but haven't figured out how to change the URL in the library to test it.
the library calls
http://api.openweathermap.org:80/data/2.5/onecall
And I believe it needs to call
http://api.openweathermap.org:80/data/3.0/onecall

**Comment by AlexeyMal** [comment]
Dear Brown-onion,
thank you for the request!
As OpenWeatherMap discontinued the free OneCallAPI 2.5 and require a (payed) subscription for API3.0 with a credit card I have decided to change the provider and just reprogrammed my weather station to use a new, free and flexible open-meteo API.
Please use my code and enjoy!
Best regards, Alexey
